In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import random
from copy import deepcopy

In [2]:
FOREST_WIDTH = 100
FOREST_LENGTH = 50

EMPTY = 0
PREY = 1
PREDATOR = -1

CELL_TYPES = [EMPTY, PREY, PREDATOR]

K = 1

P1 = 0.5
P2 = 0.5
P3 = 0.5

NUM_RUNS = 2

In [3]:
def init_forest():
    forest = []
    for i in range(FOREST_WIDTH):
        row = [PREY]*(FOREST_LENGTH - 20) + [PREDATOR]*20
        random.shuffle(row)
        forest.append(row)
    return forest

In [4]:
def find_neighbours(arr, row_number, column_number, k):
    neighbours = set()
    for i in range(row_number - 1 - k + 1, row_number + k + 1):
        for j in range(column_number - 1 - k + 1, column_number + k + 1):
            if i >= 0 and i < len(arr) and j >= 0 and j < len(arr[0]):
                 neighbours.add((arr[i][j], (i, j)))
    neighbours.remove((arr[row_number][column_number], (row_number, column_number)))
    return neighbours

In [5]:
def get_random_neighbouring_cell(arr, row_number, column_number, k):
    return random.sample(find_neighbours(arr, row_number, column_number, k), 1)

In [6]:
def update_forest_cell(forest, row_number, column_number, k, p1, p2, p3):
    updated_forest = deepcopy(forest)    
    
    if updated_forest[row_number][column_number] == EMPTY:
        neighbouring_cell = get_random_neighbouring_cell(updated_forest, row_number, column_number, k)
        if neighbouring_cell[0] == PREY:
            if random.random() < p1:
                updated_forest[row_number][column_number] = PREY
                
    elif updated_forest[row_number][column_number] == PREY:
        neighbouring_cell = get_random_neighbouring_cell(updated_forest, row_number, column_number, k)
        if neighbouring_cell[0] == PREDATOR:
            if random.random() < p2:
                updated_forest[row_number][column_number] = PREDATOR
                
    elif updated_forest[row_number][column_number] == PREDATOR:
        if random.random() < p3:
            updated_forest[row_number][column_number] = EMPTY
    
    return updated_forest

In [7]:
def update_forest(forest, k, p1, p2, p3):
    updated_forest = deepcopy(forest)
    for i in range(len(forest)):
        for j in range(len(forest[0])):
            updated_forest[i][j] = update_forest_cell(forest, i, j, k, p1, p2, p3)[i][j]
    return updated_forest

In [8]:
def update_forest_runs(forest, runs, k, p1, p2, p3):
    updated_forest_after_runs = deepcopy(forest)
    for run in range(runs):
        updated_forest = update_forest(updated_forest_after_runs, k, p1, p2, p3)
        updated_forest_after_runs = deepcopy(updated_forest)
        
    return updated_forest_after_runs

In [9]:
forest = np.array(init_forest())

In [10]:
print(find_neighbours(forest, 0, 0, 1))
print(get_random_neighbouring_cell(forest, 0, 0, 2))

{(1, (0, 1)), (1, (1, 1)), (1, (1, 0))}
[(1, (0, 1))]


In [11]:
updated_forest = np.array(update_forest(forest, K, P1, P2, P2))
update_forest_after_runs = np.array(update_forest_runs(forest, NUM_RUNS, K, P1, P2, P3))

In [12]:
forest

array([[ 1,  1, -1, ...,  1,  1,  1],
       [ 1,  1, -1, ..., -1,  1,  1],
       [ 1,  1,  1, ...,  1,  1, -1],
       ...,
       [-1, -1,  1, ...,  1, -1,  1],
       [-1, -1,  1, ..., -1,  1,  1],
       [ 1, -1, -1, ...,  1,  1, -1]])

In [13]:
updated_forest

array([[ 1,  1,  0, ...,  1,  1,  1],
       [ 1,  1, -1, ..., -1,  1,  1],
       [ 1,  1,  1, ...,  1,  1, -1],
       ...,
       [ 0, -1,  1, ...,  1,  0,  1],
       [-1,  0,  1, ...,  0,  1,  1],
       [ 1,  0, -1, ...,  1,  1, -1]])

In [14]:
update_forest_after_runs

array([[ 1,  1, -1, ...,  1,  1,  1],
       [ 1,  1,  0, ...,  0,  1,  1],
       [ 1,  1,  1, ...,  1,  1, -1],
       ...,
       [ 0,  0,  1, ...,  1, -1,  1],
       [ 0,  0,  1, ...,  0,  1,  1],
       [ 1,  0, -1, ...,  1,  1,  0]])